config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "dashboard#index"
  resources :projects, :only => [:index, :show]
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
	belongs_to :project
	belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :projects_user, :dependent => :destroy
  	has_many :users, :through => :projects_user
  	has_many :tasks

  	validates_presence_of :status, :name, :planned_hours, :start_date
  	validates_numericality_of :planned_hours

  	def self.statuses
    	['In Progress', 'Closed', 'Pending']
  	end

  	def member_names
  		names = self.users.pluck(:name).join(",")
  	end
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
	belongs_to :project
  	belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
	require 'csv'
	belongs_to :project
	belongs_to :user

	validates_presence_of :project_id, :user_id, :task_name, :total_hours, :start_date
  	validates_numericality_of :total_hours

  def self.to_csv
  	CSV.generate do |csv|
	 		## Header values of CSV
	    csv << ["Task","Project","User","Hours","Start Date","End Date"]
      all.each do |task|
      	csv << [task.task_name,task.project.try(:name),task.user.try(:name),task.total_hours,task.start_date.try(:strftime,"%Y-%b-%d"),task.end_date.try(:strftime,"%Y-%b-%d")]
  		end
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects_user, :dependent => :destroy
  has_many :projects, :through => :projects_user
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_sanitized_params, if: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def update_sanitized_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	if params[:project_id] && (params[:project_id] != "")
      @tasks = current_user.tasks.where(project_id: params[:project_id])
    else
      @tasks = current_user.tasks
    end
    @projects = current_user.projects
    respond_to do |format|
      format.html
      format.csv { send_data @tasks.to_csv }
      format.xls
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy,:show]
  def index
    if params[:project_id] && (params[:project_id] != "")
      @projects = current_user.projects.where(id: params[:project_id])
    else
      @projects = current_user.projects
    end
    respond_to do |format|
      format.html 
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  private

  def project_params
    params.require(:project).permit(:name, :status, :start_date, :end_date, :planned_hours, :project_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    if params[:project_id] && (params[:project_id] != "")
      @tasks = current_user.tasks.where(project_id: params[:project_id])
    else
      @tasks = current_user.tasks
    end
    @projects = current_user.projects
    respond_to do |format|
      format.html
      format.csv { send_data @tasks.to_csv }
      format.xls
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task

      @task = current_user.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_name, :user_id, :total_hours, :start_date, :end_date, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/index.html.erb
<div class = "dash-titles">
  <h1>Dashboard</h1>
  <h2>Tasks</h2>
</div>
<div class="task-btn"><a href="<%= new_task_path %>"><button type="button">New Task</button></a></div>
<div class="search-blk">
  <%= form_tag(dashboard_index_path, method: :get) do %>
    <%= select_tag(:project_id, options_for_select(@projects.map { |p| [p.name, p.id] },params[:project_id]), include_blank: 'Select')%>
    <%= submit_tag 'Search', name: nil %>
  <% end %>
</div>
<div class="dash-tasks">
  <table>
    <thead>
      <tr>
        <th>Task</th>
        <th>Project</th>
        <th>Hours</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
    	<% for task in @tasks %>
    		<div class='task'>
      		<tr>
          	<td>
              <strong> <%= task.task_name %> </strong>
            </td>
            <td><%= task.project.try(:name) %></td>
            <td><%= task.total_hours %></td>
            <td><%= task.start_date.try(:strftime,"%Y-%b-%d") %></td>
            <td><%= task.end_date.try(:strftime,"%Y-%b-%d") %></td>
            <td><%= link_to 'Details', task_path(task) %></td>
          </tr>
        </div>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Download as CSV", controller:'tasks',action:'index',format: :csv,project_id: params[:project_id] %> |
  <%= link_to "Excel", controller:'tasks',action:'index',format: :xls,project_id: params[:project_id] %>
</div>

app/views/layouts/_navbar.html.erb
<div class="menu">
	<ul>
		<li><%= link_to('Home', dashboard_index_path)%></li>
    <li><%= link_to('Project', projects_path)%></li>
		<li><%= link_to('Logout', destroy_user_session_path, :method => 'delete')%></li>
	</ul>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" unless (current_page?(new_user_session_path)||current_page?(user_session_path)||current_page?(new_user_registration_path)||current_page?(new_user_password_path))%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>
<%= form_tag(projects_path, method: :get) do %>
  <%= select_tag(:project_id, options_for_select(@projects.map { |p| [p.name, p.id] },params[:project_id]), include_blank: 'Select')%>
  <%= submit_tag 'Search', name: nil %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Status</th>
      <th>Planned Hours</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
  	<% for project in @projects %>
  		<div class='task'>
    		<tr>
        	<td>
            <strong> <%= project.name %> </strong>
          </td>
          <td><%= project.status %></td>
          <td><%= project.planned_hours %></td>
          <td><%= project.start_date.try(:strftime,"%Y-%b-%d") %></td>
          <td><%= project.end_date.try(:strftime,"%Y-%b-%d") %></td>
          <td><%= link_to 'Details', project_path(project) %></td>
        </tr>
      </div>
    <% end %>
  </tbody>
</table>

app/views/projects/show.html.erb
<div class = "pt-title">
<h1><%=@project.name.upcase%></h1>
</div>
<div class = "pt-details">
<h3>Details </h3>
</div>
<table>
  <tbody>
  	<tr>
  		<th>Project Name</th>
  		<td><%=@project.name.upcase%></td>
  	</tr>
  	<tr>
  		<th>Description</th>
  		<td><span><%=@project.desc%></span></td>
  	</tr>
  	<tr>
  		<th>Status</th>
  		<td><%=@project.status%></td>
  	</tr>
  	<tr>
  		<th>Members</th>
  		<td><span><%=@project.member_names%></span></td>
  	</tr>
  	<tr>
  		<th>Planned Hours</th>
  		<td><%=@project.planned_hours%></td>
  	</tr>
  	<tr>
  		<th>Start Date</th>
  		<td><%=@project.start_date.try(:strftime,"%Y-%b-%d")%></td>
  	</tr>
  	<tr>
  		<th>End Date</th>
  		<td><%=@project.end_date.try(:strftime,"%Y-%b-%d")%></td>
  	</tr>
  	<tr>
  		<th>Created At</th>
  		<td><%=@project.created_at.try(:strftime,"%Y-%b-%d")%></td>
  	</tr>
  </tbody>
</table>

app/views/tasks/_form.html.erb
<div class="task-form">
  <%= form_with(model: @task, local: true) do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <table>
      <tbody>
        <tr>
          <div class="field">
            <th><%= form.label :task %></th>
            <td><%= form.text_field :task_name, id: :task_title %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= form.label :project %></th>
            <td><%= form.select :project_id, Project.all.collect { |p| [ p.name, p.id ] }, include_blank: 'Select' %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= form.label :hours %></th>
            <td><%= form.text_field :total_hours, id: :task_total_hours %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= form.label :start_date %></th>
            <td><%= form.date_field :start_date, id: :task_start_date %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= form.label :end_date %></th>
            <td><%= form.date_field :end_date, id: :task_end_date %></td>
          </div>
        <tr>
          <div class="field">
            <th> </th>
            <td><%= form.hidden_field :user_id, :value => current_user.id %></td>
          </div>
        </tr>
        <tr>
          <div class="actions">
            <th> </th>
            <td><%= form.submit %></td>
          </div>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>New Task</h1>
<%= render 'form'%>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Task</Data></Cell>
        <Cell><Data ss:Type="String">Project</Data></Cell>
        <Cell><Data ss:Type="String">User</Data></Cell>
        <Cell><Data ss:Type="String">Hours</Data></Cell>
        <Cell><Data ss:Type="String">Start Date</Data></Cell>
        <Cell><Data ss:Type="String">End Date</Data></Cell>
      </Row>
    <% @tasks.each do |task| %>
      <Row>
        <Cell><Data ss:Type="String"><%= task.task_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= task.project.try(:name) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= task.user.try(:name) %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= task.total_hours %></Data></Cell>
        <Cell><Data ss:Type="String"><%= task.start_date.try(:strftime,"%Y-%b-%d") %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= task.end_date.try(:strftime,"%Y-%b-%d") %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/tasks/new.html.erb
<div class="new-tsk-ttl"><h1>New Task</h1></div>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class = "pt-title">
<h1><%=@task.task_name.upcase%></h1>
</div>
<div class = "pt-details">
<h3>Details </h3>
</div>
<table>
  <tbody>
  	<tr>
  		<th>Task :</th>
  		<td><%=@task.task_name.capitalize%></td>
  	</tr>
  	<tr>
  		<th>Project :</th>
  		<td><span><%=@task.project.try(:name)%></span></td>
  	</tr>
  	<tr>
  		<th>User :</th>
  		<td><%=@task.user.try(:name)%></td>
  	</tr>
  	<tr>
  		<th>Hours :</th>
  		<td><%=@task.total_hours%></td>
  	</tr>
  	<tr>
  		<th>Start Date</th>
  		<td><%=@task.start_date.try(:strftime,"%Y-%b-%d")%></td>
  	</tr>
  	<tr>
  		<th>End Date</th>
  		<td><%=@task.end_date.try(:strftime,"%Y-%b-%d")%></td>
  	</tr>
  	<tr>
  		<th>Created At</th>
  		<td><%=@task.created_at.try(:strftime,"%Y-%b-%d")%></td>
  	</tr>
  </tbody>
</table>
<div><%= link_to "Delete", task_path(@task), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%></div>
<div><%= link_to 'Update', edit_task_path(@task) %></div>